spring:
  cache:
    type: ehcache
    ehcache:
      config: classpath:ehcache.xml

datasource:
  enabled: true
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/xxx_job?useUnicode=true&characterEncoding=utf-8&useSSL=true
  user-name: root
  password: 1234
