server:
  port: 8084

spring:
  kafka:
    bootstrap-servers: 10.51.225.82:9092,10.51.225.84:9092,10.51.225.86:9092
    # consumer消费者
    consumer:
      # 默认的消费组ID
      group-id: defaultConsumerGroup
      # 是否自动提交offset
      enable-auto-commit: true
      # 提交offset延时(接收到消息后多久提交offset)
      auto-commit-interval: 5000
      # earliest:当各分区下有已提交的offset时，从提交的offset开始消费；无提交的offset时，从头开始消费
      # latest:当各分区下有已提交的offset时，从提交的offset开始消费；无提交的offset时，消费新产生的该分区下的数据
      # none:topic各分区都存在已提交的offset时，从offset后开始消费；只要有一个分区不存在已提交的offset，则抛出异常
      auto-offset-reset: earliest
      # 读Kafka数据，key采用的反序列化方式
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      # 读Kafka数据，数据采用的反序列化方式
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      # 消费端监听的topic不存在时，项目启动会报错(关掉)
      missing-topics-fatal: false
      # 设置批量消费
      # type: batch
      # 批量消费每次最多消费多少条消息
      # max-poll-records: 50


ftp:
  # 是否启用ftp-start
  enabled: true
  # ftp服务器地址
  host: 10.51.225.90
  # ftp服务器账号
  userName: ftpuser_out
  # ftp服务器密码
  password: cdmtc@scwx111
  # 被动模式
  passive-mode: true
  # 默认路径
  base-path: /data/rw_out

kakfa:
  # kafkatopic队列名称
  topics: reportdel
  groupId: xxxxx


#外网ftp文件上传
inside:
  #外网指令文件路径
  interfacePath: interface_out01
  #外网附件文件路径
  filePath: interface_out02
